# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task" unless RUBY_VERSION < "2.5"

RSpec::Core::RakeTask.new(:spec)

require "standard/rake"

task default: %i[spec standard]
